### ISSUE TITLE
it does not work at all !!!! 

### ISSUE THREAD

**Issue by alirezaahmadi** [petoknm/NRF24L01#3]

**Comment by petoknm** [comment]
Please provide additional information on what does not work, otherwise the issue will be dismissed.

**Comment by alirezaahmadi** [comment]
actually write/read register commands work well. but push and pull or send and receive functions not. I have debbuged all, I think the problem with send and receive fictions was related to the Busy flag. maybe, if you could provide an example of send and receive, simply could solve all doubts. 
thank you.

**Comment by petoknm** [comment]
I dont have an example handy, but @savent404 could. As far as I know he got it working just fine. So @savent404 could you please provide a simple example? Thank you 😄

**Comment by cwhavener** [comment]
Where is the CSN gpio pin init. CE and IRQ are init in NRF_SetupGPIO but CSN is not

**Comment by savent404** [comment]
indeed,I'll change it right now

**Comment by savent404** [comment]
@cwhavener work now?

**Comment by cwhavener** [comment]
I dont see a change

**Comment by savent404** [comment]
`static NRF_RESULT NRF_SetupGPIO(nrf24L01_Dev* dev) {

	GPIO_InitTypeDef GPIO_InitStructure;

	// CE pin
	GPIO_InitStructure.Pin = dev->NRF_CE_GPIO_PIN;
	GPIO_InitStructure.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStructure.Speed = GPIO_SPEED_MEDIUM;
	GPIO_InitStructure.Pull = GPIO_NOPULL;

	HAL_GPIO_Init(dev->NRF_CE_GPIOx, &GPIO_InitStructure);
	// end CE pin

	// IRQ pin
	GPIO_InitStructure.Mode = GPIO_MODE_IT_FALLING;
	GPIO_InitStructure.Pull = GPIO_PULLUP;
	GPIO_InitStructure.Pin = dev->NRF_IRQ_GPIO_PIN;
	HAL_GPIO_Init(dev->NRF_IRQ_GPIOx, &GPIO_InitStructure);

	/* Enable and set EXTI Line Interrupt to the given priority */
	HAL_NVIC_SetPriority(dev->NRF_IRQn, dev->NRF_IRQ_preempt_priority,
						 dev->NRF_IRQ_sub_priority);
	HAL_NVIC_EnableIRQ(dev->NRF_IRQn);
	// end IRQ pin

	NRF_CS_RESETPIN(dev);
	NRF_CE_RESETPIN(dev);

	return NRF_OK;
}`

**Comment by savent404** [comment]
@alirezaahmadi there is a demo code for you, sorry for too late
