### ISSUE TITLE
Please provide a sufficient example

### ISSUE THREAD

**Issue by desertkun** [petoknm/NRF24L01#6]
I am having troubles with a simple setup of two STM32F103's to communicate each other using NRF24L01. So I have read the source code from cover to cover to find out what might be causing it, and I still get `MaxRetransmits reached` interrupt.

I know you have included `demo.c` but it is not sufficient enough, as it not even working to begin with. Could you please attach a working project (if you have one you can share) or update the `demo.c`?

**Comment by savent404** [comment]
it will comming soon, emmm.. sunday this week or monday in next week

**Comment by nagygabor93** [comment]
I can't get it to work unfortunatelly. The RX/TX interrupts never triggered, only the MaxRetransmits interrupt. I'm waiting for the example :) I will try to debug it.

**Comment by desertkun** [comment]
@nagygabor93 have you configured addresses right? If you're using auto-acknowledge, you should have configure TX, RX_0 and RX_1.

<img width="500" src="https://user-images.githubusercontent.com/1666014/36872561-551fe8d8-1dae-11e8-9826-fe027fc40d77.png">

(That didn't help me anyway but might help you)

**Comment by nagygabor93** [comment]
For the transmitter, there are data in the FIFO, something is wrong with the receiver part. Can you share your config?

**Comment by desertkun** [comment]
Same. I had to essentially to review the whole library and have thousands of changes here and there, yet it does not receive the data. 

I've tried:
* set `RetransmitCount` to zero 
* modified `NRF_EnableAutoAcknowledgement` to have a way to disable auto-acknowledge
* disabled CRC check with `NRF_EnableCRC(dev, 0)`
* simply polling the device on the off chance IRQ doesn't work
* changed channel number as it might interfere with bluetooth or wifi
* changed data rate
* changed rate of the SPI itself
* checking if the packed actually ends up in TX pool before sending

No luck. I cannot either prove that it actually sends it, as `Carrier Detect` flag on the receiver remains silent. Unfortunately, I have no equipment to check if the wave actually get generated.

What I have not tried yet, though, is to send dummy carrier wave and check of the `Carrier Detect` again:

<img src="https://user-images.githubusercontent.com/1666014/36875087-369ca33e-1db7-11e8-948b-42f4969f1cac.png" height="405">

Have you tried adding a capacitor like most google results advice?

**Comment by nagygabor93** [comment]
I was able to send something and raise the RX interrupt by disabling EN_AA. But i get a hard fault interrupt here:

![image](https://user-images.githubusercontent.com/36972038/36911595-4a366ee2-1e44-11e8-9d27-7dd3d497a4f2.png)

I'm not experienced in debugging hard faults unfortunatelly...

**Comment by nagygabor93** [comment]
Okay now it's working for me with turned off EN_AA. There are some bugs in the code btw, or it is a problem with Keil compiler:

![image](https://user-images.githubusercontent.com/36972038/36913557-a61532f6-1e4a-11e8-976d-04376c6a7c56.png)

The Read Payload function is called with a uint8* RX_Buffer, but when the len in the function is bugger than 1 it will throw a hard fault exp, I dont know why. I changed the dev->RX_BUFFER definition to a uint8 RX_BUFFER[32] array.

The second thing i found that the dev->BUSY_FLAG is not volatile so the compiler optimalize the following code snipet, it will always stay in the while loop even when the IRQ handler clear the flag:

![image](https://user-images.githubusercontent.com/36972038/36913717-235ff976-1e4b-11e8-9c45-84bf1f5f820d.png)

The last thing is to debug the EN_AA. But anyway its a good lib!

**Comment by nagygabor93** [comment]
The other problem is that the 0 and 1 pipes are enabled by default, but the width is 0 for both of them. So you have to disable pipe 1 or set payload width. I think it will solve the EN_AA problem too. It's just missing from the Init function.

**Comment by desertkun** [comment]
About `dev->RX_BUFFER`, you have to initialize it with reference to your buffer, as you do with `TX_ADDRESS` and `RX_ADDRESS`. I also marked `dev->BUSY_FLAG` as volatile, still it didn't help.

So you were able to receive the data with `EN_AA` disabled? If so, I now suspect my ships to be defective.

Do your chips look like this:

<img src="https://user-images.githubusercontent.com/1666014/36919605-92ad7c84-1e66-11e8-93a8-ea88e584d5a0.png" height="300">

?

I have to items missing off PCB, do you have them as well?

**Comment by petoknm** [comment]
Yea the volatility of the busy flag is definitely an issue... Easily fixable fortunately... And all the other issues will hopefully get resolved with a working example soon... Maybe i can try to validate it this weekend but i have a lot of work so no promises...

**Comment by nagygabor93** [comment]
desertkun: i have the mini version of the board: 

![image](https://user-images.githubusercontent.com/36972038/36924829-7f4de674-1e70-11e8-9444-fd34bd617fbc.png)

For your version, lot of google search suggest a cap between vdd and gnd.

**Comment by desertkun** [comment]
@petoknm Thank you very much for the added example. I see you pretty much refactored the whole library. But I am still having troubles with this.

I managed to pull the whole thing off now, but I had to make several fixes:

1) I see you removed the `csn_set` / `csn_reset`. Datasheet says `Every new command must be started by a high to low transition on CSN.`. Until I did put those back I wasn't even able to read registers with your updates.

2) There is no documentation about `nrf_irq_handler` has to be called. I had to call it myself from `HAL_GPIO_EXTI_Callback`.

3) `tx_buffer` in `nrf24l01` struct is useless, so I removed it.

4) Despite doing `nrf_rx_tx_control(dev, NRF_STATE_RX)` during `nrf_init` the module actually inits into `TX` mode, because `ce_set(dev)` at the end is missing. That whole time I wasn't able to receive packed via interrupt, because this pin wasn't set high.

5) Removed `nrf_receive_packet` and `nrf_pull_packet` in favor of new `__weak nrf_packet_received`. Polling for new packets is not sufficient enough, so I made a handler function that has to be overrided. It is called directly inside of the interrupt.  That leaves synchronous use of the library out, but I am fine with that. 

The fixes are [here](https://github.com/desertkun/NRF24L01/commit/94a68ff06977d93a7dbdcdf564a5c95c2c9ed367), If you'd like to have a pull request, I would be happy to provide one.

**Comment by petoknm** [comment]
@desertkun I'd be happy to look at the PR and merge stuff that is relevant. So please just make the PR and we can discuss more in there. I will have to make sure to separate changes that are specific to your setup and changes that are general and only pull those in. This means I'll probably need to spend some time with the datasheet again :smile:.

**Comment by desertkun** [comment]
Resolved by #7
